name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: .NET setup
        uses: actions/setup-dotnet@v4

      - name: Dependencies restoration
        run: dotnet restore

      - name: Static code analysis
        run: dotnet format --verify-no-changes
